# SwiftLint設定ファイル

# 除外するパス
excluded:
  - Pods
  - build
  - .build
  - DerivedData
  - vendor

# 無効にするルール
disabled_rules:
  - trailing_whitespace

# オプトインルール（明示的に有効化）
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - vertical_parameter_alignment_on_call

# 行の長さ
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

# ファイルの行数
file_length:
  warning: 500
  error: 1000

# 関数の行数
function_body_length:
  warning: 50
  error: 100

# 型の行数
type_body_length:
  warning: 300
  error: 500

# ネストの深さ
nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

# 識別子の長さ
identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - URL
    - x
    - y

# 型名
type_name:
  min_length: 3
  max_length: 40

# カスタムルール
custom_rules:
  # print()の使用を警告
  no_print:
    name: "Print statement"
    regex: "print\\("
    match_kinds:
      - identifier
    message: "print()の使用は本番環境で削除してください"
    severity: warning
